import InputError from '@/Components/InputError';
import TextInput from '@/Components/TextInput';
import PageHeader, { BackIcon } from '@/Components/PageHeader';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Head, Link, useForm } from '@inertiajs/react';

const fields = [['code', 'Code fournisseur'], ['appellation', 'Appellation'], ['telephone', 'Telephone'], ['telex', 'Telex'], ['adresse', 'Adresse', 'textarea'], ['rc_autres', 'RC et informations administratives', 'textarea'], ['cb_autres', 'Informations bancaires', 'textarea'], ['artv', 'ARTV / fiscalite', 'textarea'], ['observation', 'Observation', 'textarea']];

export default function Form({ fournisseur = null }) {
    const editing = Boolean(fournisseur);
    const { data, setData, post, put, processing, errors } = useForm(Object.fromEntries(fields.map(([name]) => [name, fournisseur?.[name] || ''])));
    const submit = (event) => { event.preventDefault(); editing ? put(route('fournisseurs.update', fournisseur.id)) : post(route('fournisseurs.store')); };
    return <AuthenticatedLayout header={<Header editing={editing} />}><Head title={editing ? 'Modifier fournisseur' : 'Ajouter fournisseur'} /><div className="px-5 pb-14 pt-7 lg:px-10"><div className="mx-auto max-w-5xl overflow-hidden rounded-3xl border border-[#dce5dd] bg-white shadow-xl shadow-[#173126]/5"><div className="border-b border-[#e7ede7] bg-[#f7faf7] px-6 py-5 sm:px-8"><p className="text-sm font-bold text-[#1b3328]">Informations du fournisseur</p><p className="mt-1 text-xs text-[#718177]">Le code et l appellation sont obligatoires.</p></div><form onSubmit={submit} data-shortcut-save className="grid gap-6 p-6 sm:grid-cols-2 sm:p-8">{fields.map(([name, label, type = 'text']) => <div key={name} className={type === 'textarea' ? 'sm:col-span-2' : ''}><label htmlFor={name} className="text-sm font-bold text-[#294337]">{label}{['code', 'appellation'].includes(name) && <span className="text-[#c2741d]"> *</span>}</label>{type === 'textarea' ? <textarea id={name} value={data[name]} onChange={(event) => setData(name, event.target.value)} rows="3" className="mt-2 block w-full rounded-xl border-[#d5e1d6] bg-[#fbfdfb] px-4 py-3 text-sm text-[#20392c] focus:border-[#2f7654] focus:ring-[#2f7654]" /> : <TextInput id={name} value={data[name]} onChange={(event) => setData(name, event.target.value)} className="mt-2 block w-full rounded-xl border-[#d5e1d6] bg-[#fbfdfb] px-4 py-3" />}<InputError message={errors[name]} className="mt-2" /></div>)}<div className="flex flex-col-reverse gap-3 border-t border-[#e7ede7] pt-6 sm:col-span-2 sm:flex-row sm:justify-end"><Link href={route('fournisseurs.index')} data-shortcut-cancel className="rounded-xl px-5 py-3 text-center text-sm font-semibold text-[#5c7163] hover:bg-[#f1f6f1]">Annuler</Link><button type="submit" disabled={processing} className="rounded-xl bg-[#e5ad45] px-5 py-3 text-sm font-bold text-[#173126] shadow-lg shadow-[#c98f24]/20 hover:bg-[#f3c361] disabled:opacity-60">{processing ? 'Enregistrement...' : editing ? 'Enregistrer les modifications' : 'Enregistrer le fournisseur'}</button></div></form></div></div></AuthenticatedLayout>;
}
function Header({ editing }) { return <PageHeader eyebrow="Referentiel fournisseurs" title={editing ? 'Modifier un fournisseur' : 'Ajouter un fournisseur'} actions={<Link href={route('fournisseurs.index')} className="btn-secondary"><BackIcon />Retour a la liste</Link>} />; }
